#!/bin/bash

echo "🚀 Solana Invoice Pay - Production Setup"
echo "========================================"
echo ""

# Check if .env.local exists
if [ -f .env.local ]; then
    echo "✓ .env.local found"
else
    echo "Creating .env.local from .env.example..."
    cp .env.example .env.local
    echo "✓ .env.local created"
fi

echo ""
echo "📝 Next Steps:"
echo ""
echo "1. Create Supabase Project:"
echo "   → Go to https://supabase.com"
echo "   → Create new project"
echo "   → Copy your credentials"
echo ""
echo "2. Update .env.local with:"
echo "   → NEXT_PUBLIC_SUPABASE_URL"
echo "   → NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   → SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "3. Generate encryption key:"
echo "   → Run: node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\""
echo "   → Add to ENCRYPTION_KEY in .env.local"
echo ""
echo "4. Run database migrations:"
echo "   → Open Supabase SQL Editor"
echo "   → Copy SQL from PRODUCTION_SETUP.md"
echo "   → Execute the SQL"
echo ""
echo "5. (Optional) Setup SendGrid:"
echo "   → Go to https://sendgrid.com"
echo "   → Get API key"
echo "   → Add to .env.local"
echo ""
echo "6. Test locally:"
echo "   → npm run dev"
echo "   → Test all features"
echo ""
echo "7. Deploy to Vercel:"
echo "   → Push to GitHub"
echo "   → Import in Vercel"
echo "   → Add environment variables"
echo "   → Deploy!"
echo ""
echo "📖 Full guide: See PRODUCTION_SETUP.md"
echo ""
